package model

import "errors"

var (
	ErrNotFound                = errors.New("not found")
	ErrInvalidID               = errors.New("invalid id")
	ErrInvalidUserName         = errors.New("invalid user name")
	ErrInvalidPassword         = errors.New("invalid password")
	ErrUserNotFoundInContext   = errors.New("user not found in context")
	ErrCannotGenerateUserToken = errors.New("cannot generate user token")
	ErrCannotValidateUserToken = errors.New("cannot validate user token")
	ErrAccessDenied            = errors.New("access denied")
	ErrUnauthorized            = errors.New("'Authorization' is required Header")
	ErrIdExists                = errors.New("this ID already exists")
	ErrUserNameExists          = errors.New("user with given name already exists")
	ErrActiveSessionExists     = errors.New("there is already an active session using your account. Use /user/logout/all API to drop it")
	ErrInvalidTestTitle        = errors.New("invalid test title")
	ErrInvalidQuestionTitle    = errors.New("invalid question title")
	ErrInvalidAnswerTitle      = errors.New("invalid answer title")
	ErrInvalidPositiveResult   = errors.New("invalid positive result")
	ErrInvalidNegativeResult   = errors.New("invalid negative result")
	ErrInvalidScoreThreshold   = errors.New("invalid score threshold")
	ErrInvalidQuestions        = errors.New("invalid questions")
	ErrInvalidAnswers          = errors.New("invalid answers")
	ErrInvalidScore            = errors.New("invalid answer score")
	ErrInvalidUserId           = errors.New("invalid userId")
	ErrInvalidTestId           = errors.New("invalid testId")
	ErrNoTestForValidation     = errors.New("no test is provided for validation of test result")
	ErrAnswersDoNotMatchTest   = errors.New("there are too many answers or answered questions or answers do not match test questions")
	ErrDuplicateQuestion       = errors.New("duplicate question")
	ErrDuplicateAnswer         = errors.New("duplicate answer")
)
